---
#####################################################################################################
# Skupper resources
#####################################################################################################
apiVersion: skupper.io/v1alpha1
kind: ProvidedService
metadata:
  name: details
spec:
  ports:
  - port: 9080
    name: http
---
