---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sites.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serviceAccount:
                  type: string
                settings:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
            status:
              type: object
              properties:
                addresses:
                  type: array
                  items:
                    type: object
                    properties:
                      host:
                        type: string
                      port:
                        type: string
                      name:
                        type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: sites
    singular: site
    kind: Site
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: requiredservices.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                address:
                  type: string
                ports:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      port:
                        type: integer
  scope: Namespaced
  names:
    plural: requiredservices
    singular: requiredservice
    kind: RequiredService
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: providedservices.skupper.io
spec:
  group: skupper.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                selector:
                  type: object
                  additionalProperties:
                    type: string
                host:
                  type: string
                address:
                  type: string
                ports:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      port:
                        type: integer
  scope: Namespaced
  names:
    plural: providedservices
    singular: providedservice
    kind: ProvidedService
---